CREATE TABLE `demo` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `create_by` varchar(64) DEFAULT NULL,
  `create_time` bigint(20) DEFAULT NULL,
  `last_update_by` varchar(64) DEFAULT NULL,
  `last_update_time` bigint(20) DEFAULT NULL,
  `record_version` bigint(20) DEFAULT NULL,
  `account_id` int(11) NOT NULL,
  `avg_unit_price` decimal(12,8) DEFAULT NULL,
  `balance_date_from` bigint(20) DEFAULT NULL,
  `balance_date_to` bigint(20) DEFAULT NULL,
  `bill_no` varchar(20) NOT NULL,
  `click_num` int(11) DEFAULT NULL,
  `conv_rate` double(9,8) DEFAULT NULL,
  `conv_rate_is_abnormal` varchar(6) DEFAULT NULL,
  `conv_rate_threshold` double(9,8) DEFAULT NULL,
  `cp_type` varchar(10) DEFAULT NULL,
  `errmsg` varchar(512) DEFAULT NULL,
  `period` varchar(8) DEFAULT NULL,
  `price` decimal(12,2) DEFAULT NULL,
  `status` varchar(10) DEFAULT NULL,
  `type` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;